name: Provision Runner
description: Provisions GitHub Actions runner with security tools.

inputs:
  wiz-sensor-token:
    description: "JSON token containing registry credentials and Wiz API client credentials"
    required: true

runs:
  using: composite
  steps:
    - name: Start Wiz Sensor
      uses: wiz-sec-public/wiz-sensor-github-action@2fd38e4d101f185b1deb0c313c0adb0a7efdfe62 # v0.9.6
      with:
        token: ${{ inputs.wiz-sensor-token }}
