name: Provision Runner
description: Provisions GitHub Actions runner with security tools

inputs:
  wiz-sensor-token:
    description: "JSON token containing registry credentials and Wiz API client credentials"
    required: true

runs:
  using: composite
  steps:
    - name: Start Wiz Sensor
      uses: wiz-sec-public/wiz-sensor-github-action@7211eb00c237dfc0ee5875c51637cd100804ddbb # v0.9.2
      with:
        token: ${{ inputs.wiz-sensor-token }}
